version: "3.8"

networks:
  default:
    driver: bridge

services:

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=${REDIS_HOST}
    command: redis-server --requirepass ${REDIS_PASSWORD}
