// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/counter/{hero}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heroes"
                ],
                "summary": "Получить информацию о персонажах, против которых заданные герой играет плохо",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя героя",
                        "name": "hero",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.HeroInfoCounterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.Error"
                        }
                    }
                }
            }
        },
        "/info/{hero}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heroes"
                ],
                "summary": "Получить информацию по заданному герою",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя героя",
                        "name": "hero",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.HeroInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.HeroInfoCounterResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "strong_opponents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.StrongOpponent"
                    }
                }
            }
        },
        "entity.HeroInfoResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "popular_lines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Line"
                    }
                }
            }
        },
        "entity.Line": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "presence": {
                    "type": "string"
                },
                "win_rate": {
                    "type": "string"
                }
            }
        },
        "entity.StrongOpponent": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "win_rate_original_hero": {
                    "type": "string"
                }
            }
        },
        "handler.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Dota2-Info-Service",
	Description:      "API Server for Dota2-Info-Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
